setulb – ROHSA
setulb Subroutine
40 statements
Source File
subroutine setulb(n, m, x, l, u, nbd, f, g, factr, pgtol, wa, iwa, task, iprint, csave, lsave, isave, dsave)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: m
double precision :: x(n)
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: f
double precision :: g(n)
double precision :: factr
double precision :: pgtol
double precision :: wa(2*m*n+5*n+11*m*m+8*m)
integer :: iwa(3*n)
character(len=60) :: task
integer :: iprint
character(len=60) :: csave
logical :: lsave(4)
integer :: isave(44)
double precision :: dsave(29)
Called by
Contents
None
Call graph
minimize_spec calls setulb
minimize calls setulb
upgrade calls minimize_spec
init_spectrum calls minimize_spec
update calls minimize