lnsrlb – ROHSA
lnsrlb Subroutine
81 statements
Source File
subroutine lnsrlb(n, l, u, nbd, x, f, fold, gd, gdold, g, d, r, t, z, stp, dnorm, dtd, xstep, stpmx, iter, ifun, iback, nfgv, info, task, boxed, cnstnd, csave, isave, dsave)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: x(n)
double precision :: f
double precision :: fold
double precision :: gd
double precision :: gdold
double precision :: g(n)
double precision :: d(n)
double precision :: r(n)
double precision :: t(n)
double precision :: z(n)
double precision :: stp
double precision :: dnorm
double precision :: dtd
double precision :: xstep
double precision :: stpmx
integer :: iter
integer :: ifun
integer :: iback
integer :: nfgv
integer :: info
character(len=60) :: task
logical :: boxed
logical :: cnstnd
character(len=60) :: csave
integer :: isave(2)
double precision :: dsave(13)
Calls
Contents
None
Call graph
lnsrlb calls dcsrch, dcopy
dcsrch calls dcstep