myfunc_spec – ROHSA
myfunc_spec Function
7 statements
Source File
private pure function myfunc_spec(residual)
Arguments
Type Intent Optional Attributes Name
real(kind=xp), intent(in), dimension(:), allocatable :: residual
Return Value real(kind=xp)
Called by
Contents
Source Code
myfunc_spec
Source Code
  pure function  myfunc_spec(residual)
    implicit none
    real(xp), intent(in), dimension(:), allocatable :: residual
    real(xp) :: myfunc_spec
    myfunc_spec = 0._xp
    myfunc_spec = 0.5_xp * sum(residual**2._xp)
  end function  myfunc_spec
Call graph
minimize_spec calls myfunc_spec
f_g_cube calls myfunc_spec
upgrade calls minimize_spec
minimize calls f_g_cube
init_spectrum calls minimize_spec
update calls minimize