ravel_3D – ROHSA
ravel_3D Subroutine
16 statements
Source File
public subroutine ravel_3D(cube, vector, dim_v, dim_y, dim_x)
Arguments
Type Intent Optional Attributes Name
real(kind=xp), intent(in), dimension(:,:,:), allocatable :: cube
real(kind=xp), intent(inout), dimension(:), allocatable :: vector
integer, intent(in) :: dim_v
integer, intent(in) :: dim_y
integer, intent(in) :: dim_x
Called by
Contents
Source Code
ravel_3D
Source Code
  subroutine ravel_3D(cube, vector, dim_v, dim_y, dim_x)
    implicit none
    integer, intent(in) :: dim_v, dim_y, dim_x
    real(xp), intent(in), dimension(:,:,:), allocatable :: cube
    real(xp), intent(inout), dimension(:), allocatable :: vector
    integer :: i, j, k, i__
    i__ = 1
    do k=1, dim_x
       do j=1, dim_y
          do i=1, dim_v
             vector(i__) = cube(i,j,k)
             i__ = i__ + 1
          end do
       end do
    end do
  end subroutine ravel_3D
Call graph
update calls ravel_3d, minimize
f_g_cube calls ravel_3d
minimize calls f_g_cube