ravel_2D – ROHSA
ravel_2D Subroutine
14 statements
Source File
public subroutine ravel_2D(map, vector, dim_y, dim_x)
Arguments
Type Intent Optional Attributes Name
real(kind=xp), intent(in), dimension(:,:), allocatable :: map
real(kind=xp), intent(inout), dimension(:), allocatable :: vector
integer, intent(in) :: dim_y
integer, intent(in) :: dim_x
Called by
Contents
Source Code
ravel_2D
Source Code
  subroutine ravel_2D(map, vector, dim_y, dim_x)
    implicit none
    integer, intent(in) :: dim_y, dim_x
    real(xp), intent(in), dimension(:,:), allocatable :: map
    real(xp), intent(inout), dimension(:), allocatable :: vector
    integer :: j, k, i__
    i__ = 1
    do k=1, dim_x
       do j=1, dim_y
             vector(i__) = map(j,k)
             i__ = i__ + 1
       end do
    end do
  end subroutine ravel_2D
Call graph
update calls ravel_2d
max_2d calls ravel_2d
std_2d calls ravel_2d
mean_2d calls ravel_2d
std_spectrum calls std_2d
max_spectrum calls max_2d
mean_spectrum calls mean_2d